[package]
name = "swcify"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
napi = "1"
napi-derive = "1"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
napi-build = "1"